# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/nmq_first_classify.ui'
#
# Created: Wed Feb 18 15:26:11 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class classify_MainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(601, 452)
        self.centralwidget = QtGui.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.file_path = QtGui.QLabel(self.centralwidget)
        self.file_path.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setWeight(75)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setBold(True)
        self.file_path.setFont(font)
        self.file_path.setCursor(QtCore.Qt.ArrowCursor)
        self.file_path.setAcceptDrops(False)
        self.file_path.setFrameShape(QtGui.QFrame.NoFrame)
        self.file_path.setObjectName("file_path")
        self.verticalLayout_3.addWidget(self.file_path)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(15, -1, 0, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.info_label = QtGui.QLabel(self.centralwidget)
        self.info_label.setFrameShape(QtGui.QFrame.Box)
        self.info_label.setLineWidth(0)
        self.info_label.setText("")
        self.info_label.setMargin(28)
        self.info_label.setIndent(6)
        self.info_label.setObjectName("info_label")
        self.verticalLayout_2.addWidget(self.info_label)
        self.attr_list = QtGui.QListWidget(self.centralwidget)
        self.attr_list.setFrameShape(QtGui.QFrame.NoFrame)
        self.attr_list.setObjectName("attr_list")
        self.verticalLayout_2.addWidget(self.attr_list)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        spacerItem = QtGui.QSpacerItem(5, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, -1, 11, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.port_label = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.port_label.setFont(font)
        self.port_label.setTextFormat(QtCore.Qt.AutoText)
        self.port_label.setObjectName("port_label")
        self.horizontalLayout_2.addWidget(self.port_label)
        self.pot_num = QtGui.QComboBox(self.centralwidget)
        self.pot_num.setObjectName("pot_num")
        self.horizontalLayout_2.addWidget(self.pot_num)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.time_label = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(False)
        self.time_label.setFont(font)
        self.time_label.setTextFormat(QtCore.Qt.AutoText)
        self.time_label.setAlignment(QtCore.Qt.AlignCenter)
        self.time_label.setMargin(2)
        self.time_label.setIndent(-1)
        self.time_label.setObjectName("time_label")
        self.horizontalLayout_3.addWidget(self.time_label)
        self.weekday = QtGui.QComboBox(self.centralwidget)
        self.weekday.setObjectName("weekday")
        self.horizontalLayout_3.addWidget(self.weekday)
        self.spe_time = QtGui.QComboBox(self.centralwidget)
        self.spe_time.setObjectName("spe_time")
        self.horizontalLayout_3.addWidget(self.spe_time)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem2 = QtGui.QSpacerItem(17, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.start_btn = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.start_btn.setFont(font)
        self.start_btn.setIconSize(QtCore.QSize(16, 16))
        self.start_btn.setObjectName("start_btn")
        self.verticalLayout.addWidget(self.start_btn)
        spacerItem3 = QtGui.QSpacerItem(20, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.rest_list = QtGui.QListWidget(self.centralwidget)
        self.rest_list.setFrameShape(QtGui.QFrame.NoFrame)
        self.rest_list.setObjectName("rest_list")
        self.verticalLayout.addWidget(self.rest_list)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        mainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        mainWindow.setWindowTitle(QtGui.QApplication.translate("mainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.file_path.setText(QtGui.QApplication.translate("mainWindow", "   C:\\", None, QtGui.QApplication.UnicodeUTF8))
        self.port_label.setText(QtGui.QApplication.translate("mainWindow", "端口号（窗口号）:", None, QtGui.QApplication.UnicodeUTF8))
        self.time_label.setText(QtGui.QApplication.translate("mainWindow", "时间段：", None, QtGui.QApplication.UnicodeUTF8))
        self.start_btn.setText(QtGui.QApplication.translate("mainWindow", "显示结果", None, QtGui.QApplication.UnicodeUTF8))

